username : "bijon.guha@siemens.com"
api_token : "ATATT3xFfGF0nLp97Dgt7AbM7ucr48ro1EO9p1ScRjTu16kmBmVM4CW8LF7Wn7LORiPqhkhx1YNrlsjPdxh-7mUHR6c0qnvSTODZ7gbNYB3jTmD5MEsQB7snz3pnvinSk-FRlt-eY_nI4RR8csOK5_2n55WwDCcjYd6fCYCWNH7T3u6MDy4SIKU=0CB1EAF3"
jira_url : "https://adv-sol.atlassian.net"
project_key : "TMA"
jira_query : 'project = TMA'